humanmade/hm-platform

- lib/cavalcade-runner-to-cloudwatch/plugin.php
- load.php
Make use of the new AWS SDK! to send metrics on Cavalcade to CloudWatch.
> Send cavalcade metrics to cloudwatch.

- lib/elasticpress-integration.php
It expects EP_HOST to be a full URL.
> Fix defines for ElascticPress plugin

- load.php
Currently it's running on local environments when people are using cavalcade.
Fixes #55
> Only include cavalcade cloudwatch integration on HM Cloud

- CHANGELOG.md
- README.md
This adds documentation on how we disable search engine indexing in non-production environments.
@joehoyle I'm wondering if we should rename the constant to `HM_FORCE_DISABLE_INDEXING` for clearer intention on what the constant/feature does?
> Document HM_DISABLE_INDEXING

- plugins/hm-stack/inc/api/namespace.php
- plugins/hm-stack/inc/rest-controller/namespace.php
Adds REST API endpoints for bandwidth-usage and page-generation, which proxy requests on the to HM Stack API (which, in turn, proxies them to the Cloudwatch API.
Connected to https://github.com/humanmade/hm-cloud-plugin/issues/3 and https://github.com/humanmade/hm-cloud-plugin/issues/1.
Still a work in progress; I'm not getting any data from the AWS/ApplicationELB API for the page generation time query, and I'm appreciate an extra set of eyes to see if I'm missing something.
> (WIP) Add bandwidth usage and page generation time endpoints

- load.php
This gives us better tracking on DB activity in XRay. It does need to overload `global $wpdb` to hook the queries correctly, which seems to be fairly unavoidable.
> Include XRay DB dropin

- CHANGELOG.md
- README.md
This just updates S3 Uploads so ID3 parsing works correctly again.  Attachments weren't having their metadata generated, this fixes that.
> Update s3-uploads to latest, fixes id3 parsing

- CHANGELOG.md
- includes/manifest.php
Adding priority of `11` to the redis plugin loads it after Batcace, causing fatals. Because it's registered at priority 10 before Batcache is registered, it will still execute after Memcached has been (potentially) set up, and before Batcache is loaded.
> Load Redis before Batcache loads, fixes fatals

- plugins/hm-stack/inc/api/namespace.php
- plugins/hm-stack/inc/rest-controller/namespace.php
Updates the endpoints in hm-stack-api plugin for bandwidth-usage and page-generation to retrieve data from HM Stack's metrics passthru, making use of the new `%current_load_balancer%` dynamic parameter as added in https://github.com/humanmade/hm-stack/pull/489.
> Update bandwidth-usage and page-generation API endpoints

- load.php
This will disable XHProf sampling for when the Cavalcade Runner starts.  As the RUnner is a long-running process, XHProf will continue to hold data in memory, leading to instances running out of memory. Disabling XHProf sampling for the runner fixes the issue.
See https://github.com/humanmade/Cavalcade-Runner/issues/48 for history
> Disable XHProf for Cavalcade-Runner.

- .gitmodules
- CHANGELOG.md
- README.md
Fix occassional provisioning error due to SSH's `known_hosts` not accepting the Github public key.
Bump version to 1.2.14 for Composer distribution.
> Change AWS Xray submodule to `https` instead of `git` protocol.

- CHANGELOG.md
- README.md
- lib/elasticpress-integration.php
This allows us to see remote request errors from ElasticPress, as they are silently swallowed right now. In these cases it _also_ will fallback to MySQL search, which is not a good default as it can cause a huge amount of load on the MySQL server.
See #91.
> Log ElasticPress errors and don't fallback to mysql

- CHANGELOG.md
- README.md
The latest plugin allows for enabling tachyon in the WP admin.
> Update tachyon plugin

- CHANGELOG.md
- README.md
- Update XRay plugin to 1.0.2
- Track Remote Requests made via the WordPress HTTP API.
> Update xray to 1.0.2

- CHANGELOG.md
- README.md
- lib/elasticpress-integration.php
This changes the method the ElasticPress integration uses to determine the authentication credentials to use with AWS. It will automatically determine which ones are best, allowing hm-platform to work in both an EC2 and ECS environment.
> Allow AWS determine which credential provider for Elasticsearch

- plugins/healthcheck/inc/cavalcade/namespace.php
- plugins/healthcheck/inc/namespace.php
- plugins/healthcheck/plugin.php
Replaces #120, but no longer needs an external service. Also, now that it's integrated into the Healthcheck plugin, this is a PR off master instead.
> Monitor Cavalcade via healthcheck

- .gitmodules
- load.php
THis allows us to require users be logged in if the hm-platform config `require-login` is set to true.
Using the hm-require-login plugin, currently on the branch https://github.com/humanmade/hm-require-login/pull/3
See #22.
> Add 'require-login' feature

- inc/cloudwatch_error_handler/namespace.php
- inc/cloudwatch_logs/namespace.php
- lib/ses-to-cloudwatch/plugin.php
- load.php
Application layer PHP error handler to send structured errors with XRay (part of the XRay plugin) integration.
I think we might only want to activate on ECS, because (though not in this PR) this uses a Log Group that doesn't exist elsewhere.
> Send PHP Logs to CloudWatch

- CHANGELOG.md
- inc/class-db.php
- load.php
We make use of a new hm-platform db dropin to bridge LudicrousDB and
XRay. Our DB dropin is _always_ used, but only a second DB server is
added if the constant is set.
We also send the different hostnames to XRay for DB queries so we
correctly the get service map showing amount of traffic to the db or the
db replica.
We also default the DB_CHARSET to utfmb4, as `wpdb` has done this for a
while, but LudicrousDB never had that functionality.
> Support for DB_READ_REPLICA_HOST

- lib/elasticsearch-integration.php
The ElasticPress integration filters any HTTP requests made to the Elasticsearch server. This includes Icspresso queries, which are made differently.
Icspresso sends some HTTP requests with an empty body, specifically an empty array. The signing code in the Elasticsearch Integration plugin doesn't account for array bodies, and this causes Request to eventually throw an exception. This causes a fatal, which is causing whitescreens when new sites are created and Icspresso tries to create an index for them.
This PR makes that code more robust, and uses the same mechanism of building the body as WP_Http (and Requests) uses internally. I've tested this in production (😱) and it allowed me to create the index for a new site which was fatalling without the patch.
tl;dr this should fix search …
> Fix Icspresso status queries

- inc/cloudwatch_logs/namespace.php
In cases where clients have disabled external object cache, this function will not yet be available. In which case we should check that. This is quite an edge-case, but vantage-backend does exactly that.
> Check if wp_cache_add_global_groups exists before calling

- inc/class-db.php
Before we switched to ludicrous (on HEAD) then a `define( "DB_COLLATE", "" )` would fall back to using utf8mb4_..., I ported this behaviour to our own drop-in for backwards comapt with existing wp-configs that may do this.
> Handle DB_COLLATE not being set

- CHANGELOG.md
- plugins/healthcheck/inc/namespace.php
We need to also check for falsy, as it's always defined.
> Don't run Elasticsearch test in helthcheck if it's not enabled

- CHANGELOG.md
- load.php
In situations where redis want's to use this "feature" it doesn't actually work, as the DB is not bootstrapped by this point in the code path. That's because we load the wpdb and object-cache slightly differently, but it any case I can't think we want this feature.
> Disable redis failback flush

- CHANGELOG.md
- inc/cloudwatch_error_handler/namespace.php
Similar to https://github.com/humanmade/aws-xray/pull/22, there are many error types not passed to the `error_handler`, but we can get these on shutdown.
> Track fatal errors on shutdown

- CHANGELOG.md
- load.php
Reverts humanmade/hm-platform#155
Turns out `$params = apply_filters( 'hm_platform.aws_sdk.params', $params );` breaks, because `apply_filters` is not available un Cavalcade at this step.
> Revert "Update AWS XRay"

- CHANGELOG.md
- load.php
Is there still any reason this shouldn't just default to enabled regardless of architecture?
Currently we're relying on project developers to know to turn it on, and that's not always happening.
> X-Ray should default to enabled

- CHANGELOG.md
- load.php
I thought this was already the case, turns out it is not. `admin-ajax.php` is often used as a quick HTTP API to power the front-end of the site for features like pagination, and we want to be caching all those requests like any other.
> Cache admin-ajax requests for logged out users
